Python django drf support (#79)
* drop support for ancient djangos, drfs and pythons
* chrome support
* safari support
* edge currently disabled as selenium doesn't support it out of the box yet
* drop nullbooleanfield as per django deprecation. using BooleanField(null=True)
* drf 3.10 does not support django 3.1
* allow chrome to fail
* allow safari to fail (huge issues with one connection, failing connections, etc)

diff --git a/.github/workflows/Python tests.yml b/.github/workflows/Python tests.yml
--- a/.github/workflows/Python tests.yml
+++ b/.github/workflows/Python tests.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python: [3.5, 3.6, 3.7, 3.8]
+        python: [3.8, 3.9]
       fail-fast: false
 
     env:
@@ -16,99 +16,46 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
-      - name: Setup Python
-        uses: actions/setup-python@v1
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install Tox and any other packages
-        run: pip install tox
       - name: Prepare Selenium enviroment
         run: |
           #Download geckodriver
           wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
           #Extract geckodriver
           tar -xvzf geckodriver*
-          #Make geckodriver execuable
+          #Make geckodriver executable
           chmod +x geckodriver
           #Move geckodriver
           sudo mv geckodriver /usr/local/bin/
 
-      - name: Run Tox py-django110-drf39
-        if: matrix.python != 3.8 && (success() || failure())
-        # Looks like tests for django 1.* are in single thread. So there are sometimes strange errors (Alert doesn't
-        # show up, redirection doesn't work, etc...)
-        continue-on-error: true
-        run: tox -e py-django110-drf39
+      - name: Setup Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python }}
+      - name: Install Tox and any other packages
+        run: pip install tox
 
-      - name: Run Tox py-django1tip-drf37
+      - name: Run Tox py-django22
         if: success() || failure()
-        # Looks like tests for django 1.* are in single thread. So there are sometimes strange errors (Alert doesn't
-        # show up, redirection doesn't work, etc...)
-        continue-on-error: true
-        run: tox -e py-django1tip-drf37
+        run: tox -e py-django22-drf310,py-django22-drf311,py-django22-drf312,py-django22-drftip
 
-      - name: Run Tox py-django1tip-drf38
+      - name: Run Tox py-django30
         if: success() || failure()
-        # Looks like tests for django 1.* are in single thread. So there are sometimes strange errors (Alert doesn't
-        # show up, redirection doesn't work, etc...)
-        continue-on-error: true
-        run: tox -e py-django1tip-drf38
+        run: tox -e py-django30-drf310,py-django30-drf311,py-django30-drf312,py-django30-drftip
 
-      - name: Run Tox py-django1tip-drf39
-        if: success() || failure()
-        # Looks like tests for django 1.* are in single thread. So there are sometimes strange errors (Alert doesn't
-        # show up, redirection doesn't work, etc...)
-        continue-on-error: true
-        run: tox -e py-django1tip-drf39
-
-      - name: Run Tox py-django1tip-drftip
-        if: success() || failure()
-        # Looks like tests for django 1.* are in single thread. So there are sometimes strange errors (Alert doesn't
-        # show up, redirection doesn't work, etc...)
-        continue-on-error: true
-        run: tox -e py-django1tip-drftip
-
-      - name: Run Tox py-django20-drf39
-        if: success() || failure()
-        run: tox -e py-django20-drf39
-
-      - name: Run Tox py-django21-drf39
-        if: success() || failure()
-        run: tox -e py-django21-drf39
-
-      - name: Run Tox py-django22-drf39
-        if: success() || failure()
-        run: tox -e py-django22-drf39
-
-      - name: Run Tox py-django22-drf38
-        if: success() || failure()
-        run: tox -e py-django22-drf38
-
-      - name: Run Tox py-django22-drftip
-        if: success() || failure()
-        run: tox -e py-django22-drftip
-
-      - name: Run Tox py-django30-drf310
-        if: matrix.python != 3.5 && (success() || failure())
-        run: tox -e py-django30-drf310
-
-      - name: Run Tox py-django30-drf311
-        if: matrix.python != 3.5 && (success() || failure())
-        run: tox -e py-django30-drf311
-
-      - name: Run Tox py-django30-drftip
-        if: matrix.python != 3.5 && (success() || failure())
-        run: tox -e py-django30-drftip
+      - name: Run Tox py-django31
+        if: (success() || failure())
+        run: tox -e py-django31-drf311,py-django31-drf312,py-django31-drftip
 
       - name: Run Tox py-djangotip-drftip
-        if: matrix.python != 3.5 && (success() || failure())
+        if: (success() || failure())
+        continue-on-error: true
         run: tox -e py-djangotip-drftip
 
   ubuntu_chrome:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python: [3.5, 3.6, 3.7, 3.8]
+        python: [3.8, 3.9]
       fail-fast: false
 
     env:
@@ -116,79 +63,36 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
+      - uses: nanasess/setup-chromedriver@master
+      - run: |
+          export DISPLAY=:99
+          chromedriver --url-base=/wd/hub &
+          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
+
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
           python-version: ${{ matrix.python }}
       - name: Install Tox and any other packages
         run: pip install tox
-      - name: Run Tox py-django110-drf39
-        if: matrix.python != 3.8 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django110-drf39
 
-      - name: Run Tox py-django1tip-drf37
+      - name: Run Tox py-django22
         if: success() || failure()
         continue-on-error: true
-        run: tox -e py-django1tip-drf37
+        run: tox -e py-django22-drf310,py-django22-drf311,py-django22-drf312,py-django22-drftip
 
-      - name: Run Tox py-django1tip-drf38
+      - name: Run Tox py-django30
         if: success() || failure()
         continue-on-error: true
-        run: tox -e py-django1tip-drf38
+        run: tox -e py-django30-drf310,py-django30-drf311,py-django30-drf312,py-django30-drftip
 
-      - name: Run Tox py-django1tip-drf39
-        if: success() || failure()
+      - name: Run Tox py-django31
+        if: (success() || failure())
         continue-on-error: true
-        run: tox -e py-django1tip-drf39
-
-      - name: Run Tox py-django1tip-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drftip
-
-      - name: Run Tox py-django20-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django20-drf39
-
-      - name: Run Tox py-django21-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django21-drf39
-
-      - name: Run Tox py-django22-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf39
-
-      - name: Run Tox py-django22-drf38
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf38
-
-      - name: Run Tox py-django22-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drftip
-
-      - name: Run Tox py-django30-drf310
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf310
-
-      - name: Run Tox py-django30-drf311
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf311
-
-      - name: Run Tox py-django30-drftip
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drftip
+        run: tox -e py-django31-drf311,py-django31-drf312,py-django31-drftip
 
       - name: Run Tox py-djangotip-drftip
-        if: matrix.python != 3.5 && (success() || failure())
+        if: (success() || failure())
         continue-on-error: true
         run: tox -e py-djangotip-drftip
 
@@ -196,8 +100,9 @@ jobs:
     runs-on: macos-latest
     strategy:
       matrix:
-        python: [3.5, 3.6, 3.7, 3.8]
+        python: [3.8, 3.9]
       fail-fast: false
+      max-parallel: 1
 
     # Da bodo delali fukcionalni testi v Safariju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/91
     env:
@@ -205,169 +110,69 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
+      - run: sudo safaridriver --enable
+
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
           python-version: ${{ matrix.python }}
+
       - name: Install Tox and any other packages
         run: pip install tox
 
-      - name: Run Tox py-django110-drf39
-        if: matrix.python != 3.8 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django110-drf39
-
-      - name: Run Tox py-django1tip-drf37
+      - name: Run Tox py-django22
         if: success() || failure()
         continue-on-error: true
-        run: tox -e py-django1tip-drf37
+        run: tox -e py-django22-drf310,py-django22-drf311,py-django22-drf312,py-django22-drftip
 
-      - name: Run Tox py-django1tip-drf38
+      - name: Run Tox py-django30
         if: success() || failure()
         continue-on-error: true
-        run: tox -e py-django1tip-drf38
+        run: tox -e py-django30-drf310,py-django30-drf311,py-django30-drf312,py-django30-drftip
 
-      - name: Run Tox py-django1tip-drf39
-        if: success() || failure()
+      - name: Run Tox py-django31
+        if: (success() || failure())
         continue-on-error: true
-        run: tox -e py-django1tip-drf39
-
-      - name: Run Tox py-django1tip-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drftip
-
-      - name: Run Tox py-django20-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django20-drf39
-
-      - name: Run Tox py-django21-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django21-drf39
-
-      - name: Run Tox py-django22-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf39
-
-      - name: Run Tox py-django22-drf38
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf38
-
-      - name: Run Tox py-django22-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drftip
-
-      - name: Run Tox py-django30-drf310
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf310
-
-      - name: Run Tox py-django30-drf311
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf311
-
-      - name: Run Tox py-django30-drftip
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drftip
+        run: tox -e py-django31-drf311,py-django31-drf312,py-django31-drftip
 
       - name: Run Tox py-djangotip-drftip
-        if: matrix.python != 3.5 && (success() || failure())
+        if: (success() || failure())
         continue-on-error: true
         run: tox -e py-djangotip-drftip
 
-  win_edge:
-    runs-on: windows-latest
-    strategy:
-      matrix:
-        python: [3.5, 3.6, 3.7, 3.8]
-      fail-fast: false
-
-    # Da bodo delali fukcionalni testi v Edge-ju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/99
-    env:
-      BROWSER_SELENIUM: 'EDGE'
-
-    steps:
-      - uses: actions/checkout@v1
-      - name: Setup Python
-        uses: actions/setup-python@v1
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install Tox and any other packages
-        run: pip install tox
-
-      - name: Run Tox py-django110-drf39
-        if: matrix.python != 3.8 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django110-drf39
-
-      - name: Run Tox py-django1tip-drf37
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drf37
-
-      - name: Run Tox py-django1tip-drf38
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drf38
-
-      - name: Run Tox py-django1tip-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drf39
-
-      - name: Run Tox py-django1tip-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django1tip-drftip
-
-      - name: Run Tox py-django20-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django20-drf39
-
-      - name: Run Tox py-django21-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django21-drf39
-
-      - name: Run Tox py-django22-drf39
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf39
-
-      - name: Run Tox py-django22-drf38
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drf38
-
-      - name: Run Tox py-django22-drftip
-        if: success() || failure()
-        continue-on-error: true
-        run: tox -e py-django22-drftip
-
-      - name: Run Tox py-django30-drf310
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf310
-
-      - name: Run Tox py-django30-drf311
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drf311
-
-      - name: Run Tox py-django30-drftip
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-django30-drftip
-
-      - name: Run Tox py-djangotip-drftip
-        if: matrix.python != 3.5 && (success() || failure())
-        continue-on-error: true
-        run: tox -e py-djangotip-drftip
+#  win_edge:
+#    runs-on: windows-latest
+#    strategy:
+#      matrix:
+#        python: [3.8, 3.9]
+#      fail-fast: false
+#
+#    # Da bodo delali fukcionalni testi v Edge-ju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/99
+#    env:
+#      BROWSER_SELENIUM: 'EDGE'
+#
+#    steps:
+#      - uses: actions/checkout@v1
+#      - name: Setup Python
+#        uses: actions/setup-python@v1
+#        with:
+#          python-version: ${{ matrix.python }}
+#      - name: Install Tox and any other packages
+#        run: pip install tox
+#
+#      - name: Run Tox py-django22
+#        if: success() || failure()
+#        run: tox -e py-django22-drf310,py-django22-drf311,py-django22-drf312,py-django22-drftip
+#
+#      - name: Run Tox py-django30
+#        if: success() || failure()
+#        run: tox -e py-django30-drf310,py-django30-drf311,py-django30-drf312,py-django30-drftip
+#
+#      - name: Run Tox py-django31
+#        if: (success() || failure())
+#        run: tox -e py-django31-drf311,py-django31-drf312,py-django31-drftip
+#
+#      - name: Run Tox py-djangotip-drftip
+#        if: (success() || failure())
+#        continue-on-error: true
+#        run: tox -e py-djangotip-drftip
